import { DESIGN_VERSION, type QuoteDesign, type TemplateId } from './types';

/** Defaults every template merges onto (Templates.md, "BASE design"). */
export const BASE: QuoteDesign = {
  version: DESIGN_VERSION,
  template: 'editorial',
  font: 'editorial',
  weight: 700,
  italic: false,
  size: 92,
  lineHeight: 1.04,
  letterSpacing: -0.02,
  textTransform: 'none',
  curve: 0.6,
  textColor: '#9B1B1E',
  textFill: null,
  glow: null,
  background: { type: 'solid', color: '#F3EEE5', color2: '#E6D6C0', angle: 160, image: null, overlay: 'auto' },
  texture: { type: 'paper', strength: 0.4 },
  align: 'center',
  blockAlign: null,
  vAlign: 'center',
  padding: 96,
  topOffset: 0,
  textWidth: 1,
  canvas: '4:5',
  radius: 36,
  composition: 'flow',
  kickerScale: 0.36,
  kickerColor: null,
  secondTransform: null,
  colGap: 0,
  highlight: '#F4CA3A',
  highlightText: null,
  frame: 'none',
  footer: false,
  header: { show: true, avatar: true, name: true, username: true, verified: true, position: 'top-left', scale: 1 },
  // The spec's prototype defaulted to "— Leou"; empty signs as "— {author}" for everyone.
  signature: { show: false, text: '', style: 'script' },
};

type Overrides = Partial<Omit<QuoteDesign, 'background' | 'texture' | 'header' | 'signature'>> & {
  background?: Partial<QuoteDesign['background']>;
  texture?: Partial<QuoteDesign['texture']>;
  header?: Partial<QuoteDesign['header']>;
  signature?: Partial<QuoteDesign['signature']>;
};

export interface TemplateInfo {
  label: string;
  description: string;
  /** Shown in the picker before the person has written anything. */
  sample: string;
  overrides: Overrides;
}

export const TEMPLATES: Record<TemplateId, TemplateInfo> = {
  editorial: {
    label: 'Editorial',
    description: 'Warm cream paper, heavy burgundy serif, large avatar header, bouncing editorial wave.',
    sample: 'Be gentle with the version of you that is still learning.',
    overrides: {},
  },
  minimal: {
    label: 'Minimal',
    description: 'Pure white, black modern sans, left-aligned, no texture.',
    sample: 'Rest is not the reward for finishing. It is part of the work.',
    overrides: {
      font: 'modern',
      weight: 500,
      size: 62,
      lineHeight: 1.28,
      letterSpacing: -0.01,
      curve: 0,
      textColor: '#141414',
      background: { type: 'solid', color: '#FFFFFF' },
      texture: { type: 'none', strength: 0 },
      align: 'left',
      padding: 120,
      header: { scale: 0.7 },
    },
  },
  midnight: {
    label: 'Midnight',
    description: 'Near-black with film grain, elegant italic serif in warm off-white.',
    sample: 'You don’t have to bloom all at once.',
    overrides: {
      font: 'elegant',
      weight: 500,
      italic: true,
      size: 90,
      lineHeight: 1.06,
      letterSpacing: 0,
      curve: 0,
      textColor: '#EFE8DA',
      background: { type: 'solid', color: '#121212' },
      texture: { type: 'film', strength: 0.6 },
      header: { scale: 0.8 },
    },
  },
  typewriter: {
    label: 'Typewriter',
    description: 'Warm paper, typewriter mono, top-left, paper texture.',
    sample: 'Say the kind thing while they’re still here to hear it.',
    overrides: {
      font: 'typewriter',
      weight: 400,
      size: 52,
      lineHeight: 1.5,
      letterSpacing: 0,
      curve: 0,
      textColor: '#2A2622',
      background: { type: 'solid', color: '#ECE2CC' },
      texture: { type: 'paper', strength: 0.6 },
      align: 'left',
      vAlign: 'top',
      padding: 120,
      header: { scale: 0.75 },
    },
  },
  journal: {
    label: 'Journal',
    description: 'Cream notebook with ruled lines matched to the line height, navy handwriting.',
    sample: 'Keep a little light in your pocket for the long days.',
    overrides: {
      font: 'hand',
      weight: 600,
      size: 94,
      lineHeight: 1.12,
      letterSpacing: 0,
      curve: 0.2,
      textColor: '#1D2B4E',
      background: { type: 'solid', color: '#F6F0E1' },
      texture: { type: 'lined', strength: 0.8 },
      align: 'left',
      vAlign: 'top',
      padding: 110,
      header: { scale: 0.75 },
      signature: { style: 'script' },
    },
  },
  modern: {
    label: 'Modern',
    description: 'Navy, heavy uppercase sans set tight and bottom-left.',
    sample: 'Slow is still moving.',
    overrides: {
      font: 'bold',
      weight: 800,
      size: 100,
      lineHeight: 0.96,
      letterSpacing: -0.03,
      textTransform: 'uppercase',
      curve: 0,
      textColor: '#F3EEE5',
      background: { type: 'solid', color: '#1C2A4A' },
      texture: { type: 'grain', strength: 0.5 },
      align: 'left',
      vAlign: 'bottom',
      padding: 96,
      header: { scale: 0.75 },
      signature: { style: 'caps' },
    },
  },
  gradient: {
    label: 'Gradient',
    description: 'Soft peach-to-lavender gradient, clean centered sans.',
    sample: 'Your pace is not a verdict.',
    overrides: {
      font: 'modern',
      weight: 600,
      size: 72,
      lineHeight: 1.16,
      letterSpacing: -0.015,
      curve: 0,
      textColor: '#1B1A17',
      background: { type: 'gradient', color: '#F2C7B3', color2: '#CFCDEB', angle: 160 },
      texture: { type: 'grain', strength: 0.45 },
      align: 'center',
      padding: 110,
      header: { scale: 0.75 },
    },
  },
  photograph: {
    label: 'Photograph',
    description: 'Full-bleed photo with an automatic readability overlay; serif text at the bottom.',
    sample: 'Some mornings, arriving is enough.',
    overrides: {
      font: 'display',
      weight: 400,
      size: 88,
      lineHeight: 1.04,
      letterSpacing: -0.01,
      curve: 0,
      textColor: '#FFFFFF',
      background: { type: 'image', color: '#2A2927', overlay: 'auto' },
      texture: { type: 'film', strength: 0.4 },
      align: 'center',
      vAlign: 'bottom',
      padding: 96,
      header: { scale: 0.8 },
      signature: { style: 'serif' },
    },
  },
  diptych: {
    label: 'Diptych',
    description: 'Two halves joined by a torn-paper strip. Light serif; one word or phrase per half.',
    sample: 'still\n\nhere',
    overrides: {
      font: 'editorial',
      weight: 300,
      size: 124,
      lineHeight: 1,
      letterSpacing: -0.025,
      curve: 0,
      textColor: '#F4F1EA',
      composition: 'columns',
      background: { type: 'split', color: '#0D0D0D', color2: '#23439B' },
      texture: { type: 'grain', strength: 0.4 },
      align: 'center',
      vAlign: 'top',
      padding: 40,
      topOffset: 0.15,
      header: { scale: 0.7 },
    },
  },
  headline: {
    label: 'Headline',
    description: 'Small kicker above a huge headline that fades dark to light, on smoky gradient.',
    sample: 'one more lap\n\nthen rest.',
    overrides: {
      font: 'bold',
      weight: 800,
      size: 200,
      lineHeight: 0.9,
      letterSpacing: -0.055,
      curve: 0,
      textColor: '#E6E6E6',
      composition: 'kicker',
      kickerScale: 0.3,
      kickerColor: '#D4D4D4',
      textFill: 'linear-gradient(90deg, #111 0%, #8e8e8e 28%, #d8d8d8 55%, #e9e9e9 100%)',
      background: { type: 'gradient', color: '#3B4249', color2: '#050607', angle: 200 },
      texture: { type: 'film', strength: 0.55 },
      align: 'left',
      vAlign: 'center',
      padding: 90,
      header: { scale: 0.7 },
    },
  },
  grain: {
    label: 'Grain',
    description: 'Heavy black-and-white grain on a gray sky; rounded bold kicker and headline.',
    sample: 'status report:\n\nstill trying.',
    overrides: {
      font: 'rounded',
      weight: 800,
      size: 128,
      lineHeight: 1.04,
      letterSpacing: -0.01,
      curve: 0,
      textColor: '#2E2E2E',
      composition: 'kicker',
      kickerScale: 0.62,
      background: { type: 'gradient', color: '#6F6F6F', color2: '#ECECEC', angle: 180 },
      texture: { type: 'heavygrain', strength: 0.85 },
      align: 'left',
      vAlign: 'top',
      padding: 130,
      topOffset: 0.06,
      header: { scale: 0.7 },
    },
  },
  pager: {
    label: 'Pager',
    description: 'Retro pager: glowing amber screen, MODE/SET labels, signal bars and three buttons.',
    sample: 'I think the me from five years ago would be proud, and a little confused.',
    overrides: {
      font: 'lcd',
      weight: 400,
      size: 74,
      lineHeight: 1.12,
      letterSpacing: 0,
      curve: 0,
      textColor: '#2A1604',
      frame: 'pager',
      background: { type: 'solid', color: '#131110' },
      texture: { type: 'grain', strength: 0.35 },
      align: 'left',
      vAlign: 'top',
      padding: 0,
    },
  },
  lcd: {
    label: 'LCD',
    description: 'Camera LCD: beige metal strip, black screen, glowing red pixel type with scanlines.',
    sample: 'Protect your peace like it pays rent.',
    overrides: {
      font: 'pixel',
      weight: 400,
      size: 118,
      lineHeight: 0.98,
      letterSpacing: 0.03,
      textTransform: 'uppercase',
      curve: 0,
      textColor: '#EE3A22',
      glow: 'rgba(255,70,30,.55)',
      frame: 'lcd',
      background: { type: 'solid', color: '#1B1511' },
      texture: { type: 'scanlines', strength: 0.6 },
      align: 'left',
      vAlign: 'center',
      padding: 0,
    },
  },
  ink: {
    label: 'Ink',
    description: 'Mottled deep red, white hand-printed capitals in the left half.',
    sample: 'I preach patience, but I am still learning it.',
    overrides: {
      font: 'print',
      weight: 400,
      size: 96,
      lineHeight: 1.12,
      letterSpacing: 0.07,
      textTransform: 'uppercase',
      curve: 0,
      textColor: '#FFFFFF',
      background: { type: 'gradient', color: '#7A171B', color2: '#3F0A0D', angle: 100 },
      texture: { type: 'mottle', strength: 0.85 },
      align: 'center',
      blockAlign: 'left',
      vAlign: 'center',
      padding: 80,
      textWidth: 0.5,
      header: { scale: 0.7 },
    },
  },
  wall: {
    label: 'Wall',
    description: 'Warm concrete wall with side light; marker lettering with a hand-drawn tilt.',
    sample: 'Who says it has to be loud?',
    overrides: {
      font: 'brush',
      weight: 400,
      size: 112,
      lineHeight: 1.12,
      letterSpacing: 0,
      curve: 0.25,
      textColor: '#221C17',
      background: { type: 'gradient', color: '#DCCBA7', color2: '#7F7262', angle: 125 },
      texture: { type: 'concrete', strength: 0.85 },
      align: 'center',
      vAlign: 'center',
      padding: 130,
      header: { scale: 0.7 },
      signature: { style: 'script' },
    },
  },
  notification: {
    label: 'Notification',
    description: 'Frosted phone-notification panel on a grainy dark background.',
    sample: 'You were never too much. You were in the wrong room.',
    overrides: {
      font: 'modern',
      weight: 400,
      size: 52,
      lineHeight: 1.3,
      letterSpacing: 0,
      curve: 0,
      textColor: '#F2F2F2',
      frame: 'notification',
      background: { type: 'gradient', color: '#3A3A3A', color2: '#141414', angle: 170 },
      texture: { type: 'heavygrain', strength: 0.6 },
      align: 'left',
      vAlign: 'center',
      padding: 56,
      footer: true,
      signature: { style: 'note', text: 'note to self' },
    },
  },
  book: {
    label: 'Book',
    description: 'Book page with faint text lines; first sentence marked with a yellow highlighter.',
    sample: 'Read this slowly.\n\nThen tell someone you are glad they exist.',
    overrides: {
      font: 'editorial',
      weight: 500,
      size: 66,
      lineHeight: 1.25,
      letterSpacing: -0.01,
      curve: 0,
      textColor: '#141414',
      composition: 'highlight',
      highlightText: '#15245C',
      background: { type: 'gradient', color: '#F1ECE2', color2: '#D9D1C2', angle: 135 },
      texture: { type: 'bookpage', strength: 0.7 },
      align: 'center',
      vAlign: 'center',
      padding: 110,
      header: { scale: 0.7 },
    },
  },
  dialogue: {
    label: 'Dialogue',
    description: 'Olive canvas; two voices side by side in hand-printed type.',
    sample: '“WHAT IF WE FALL?”\n\nthen we fall together.',
    overrides: {
      font: 'print',
      weight: 400,
      size: 88,
      lineHeight: 1.12,
      letterSpacing: 0.06,
      textTransform: 'uppercase',
      secondTransform: 'none',
      curve: 0,
      textColor: '#F6F2E8',
      composition: 'columns',
      colGap: 90,
      background: { type: 'solid', color: '#57561F' },
      texture: { type: 'canvas', strength: 0.8 },
      align: 'center',
      vAlign: 'center',
      padding: 80,
      header: { scale: 0.7 },
    },
  },
};

/** BASE with a template's overrides merged in (nested objects merge one level deep). */
export function createDesign(template: TemplateId = 'editorial'): QuoteDesign {
  const o = TEMPLATES[template].overrides;
  return {
    ...BASE,
    ...o,
    template,
    background: { ...BASE.background, ...o.background },
    texture: { ...BASE.texture, ...o.texture },
    header: { ...BASE.header, ...o.header },
    signature: { ...BASE.signature, ...o.signature },
  };
}

/**
 * Switches template: the style changes, but the person's header toggles,
 * signature text, canvas and photo carry over.
 */
export function applyTemplate(design: QuoteDesign, template: TemplateId): QuoteDesign {
  const next = createDesign(template);
  const { show, avatar, name, username, verified } = design.header;
  const photo = design.background.type === 'image' ? design.background : null;
  return {
    ...next,
    canvas: design.canvas,
    header: { ...next.header, show, avatar, name, username, verified },
    signature: { ...next.signature, show: design.signature.show, text: design.signature.text },
    background: next.background.type === 'image' && photo ? { ...next.background, image: photo.image, path: photo.path } : next.background,
  };
}
